from entities.admin_staff import *
from entities.assessments import *
from entities.attendance import *
from entities.attendance_summary import *
from entities.audit_logs import *
from entities.book_issues import *
from entities.class_schedules import *
from entities.course_offerings import *
from entities.courses import *
from entities.departments import *
from entities.documents import *
from entities.enrollments import *
from entities.exam_schedules import *
from entities.exam_timetables import *
from entities.faculty import *
from entities.fee_payments import *
from entities.fee_structures import *
from entities.grades import *
from entities.hostel_allocations import *
from entities.hostel_rooms import *
from entities.hostels import *
from entities.library_books import *
from entities.notifications import *
from entities.parents import *
from entities.programs import *
from entities.semester_results import *
from entities.students import *
from entities.system_logs import *
from entities.timetable_slots import *
from entities.universities import *
from entities.user import *
from entities.user_notifications import *
